### ISSUE TITLE
IOError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by azarshab-saeed** [samuraitaiga/py-metatrader#10]
Today, I got the following error when I ran the sample example on the page below:
https://pypi.python.org/pypi/metatrader/0.0.1 :

The error log is below
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\metatrader\backtest.py", line 152, in run
    ret = BacktestReport(self)
  File "C:\Python27\lib\site-packages\metatrader\report.py", line 89, in __init
_
    with open(report_file, 'r') as fp:
IOError: [Errno 2] No such file or directory: 'C:\\Users\\azarshab\\AppData\\Ro
ming\\MetaQuotes\\Terminal\\287469DEA9630EA94D0715D755974F1B\\Moving Average.ht
'
Can anyone help me fix this?

**Comment by maxpy** [comment]
Same Issue happend
