### ISSUE TITLE
No path find

### ISSUE THREAD

**Issue by vokai** [samuraitaiga/py-metatrader#7]
Hi, I'm on linux and I don't have:

"initizalize('C:\\Program Files\\FXCM MetaTrader 4')"
how can I solve?

**Comment by Qoyyuum** [comment]
You could just change it to `import os` and use `basepath` to MT4 or just do `/full/path/to/metatrader 4` wherever that may be installed.

**Comment by ValeriChakarov** [comment]
Hi, I am using py-metatrader on Windows 10 and I am also using Pycharm.  I installed py-metatrader from the anaconda3 terminal as I have done many times before.

Today, I got the following error when I ran the sample example on the page below:
https://pypi.python.org/pypi/metatrader/0.0.1 :

The error log is below

Traceback (most recent call last):
  File "..../translator.py", line 2, in <module> 
    from metatrader.backtest import BackTest
  File "C:\anaconda3\lib\site-packages\metatrader\backtest.py", line 9, in <module>
    from mt4 import get_mt4
ModuleNotFoundError: No module named 'mt4'
'
